# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16fd851631b7c5816f753b18e4057b67060284c66952ac76ff22e3a5aff06b013e37d26ac5dbcf9707b54a8ce2174fe6320203fde02ab7e2886425b2aaf2abe9

test:
  secret_key_base: 7a7b6e2c69ff1ae0c2637038f50545f3dcc71dd3f774c78aaf15b859537bb2138a55c826b8502652f514afbda1427626060beb83aaa9977de0ff619c884246de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
